[workspace]
resolver = "3"
members = ["crates/vn-lunar-core"]
default-members = ["crates/vn-lunar-core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT"
repository = "https://github.com/FelixTNG/vn-lunar-calendar"
description = "Vietnamese Lunar Calendar Library"
authors = ["Felix <felix.tunguyen@gmail.com>"]
categories = ["date-and-time", "wasm"]
keywords = ["lunar", "calendar", "vietnam", "am-lich", "lich-am"]
readme = "README.md"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
